name: CI/CD Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"
  push:
    branches:
      - master
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Grant execute permissions to mvnw
        run: chmod +x mvnw

      - name: Set up Git
        run: |
          git config --global user.email "tv.thinh2000@gmail.com"
          git config --global user.name "Van Thinh"

      - name: Get Committer Information
        id: commit_info
        run: |
          echo "author=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          # Generate unique tag name based on current timestamp
          tag=$(date +'%Y%m%d%H%M%S')
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Spring Boot application with retries
        run: |
          retries=3
          success=false
          until $success || [ $retries -eq 0 ]; do
            ./mvnw jasypt:decrypt -Djasypt.encryptor.password=${{ secrets.JAS_PWD }} -Djasypt.plugin.path=file:src/main/resources/application.properties clean compile exec:java && success=true || ((retries--))
          done
          if ! $success; then
            echo "Failed to build Spring Boot application after multiple retries"
            exit 1
          fi