name: CI/CD Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"
  push:
    branches:
      - master
    tags:
      - v*



permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Grant execute permissions to mvnw
        run: chmod +x mvnw

      - name: Set up Git
        run: |
          git config --global user.email "tv.thinh2000@gmail.com"
          git config --global user.name "Van Thinh"

      - name: Get Committer Information
        id: commit_info
        run: |
          echo "author=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV


      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Spring Boot application
        run: ./mvnw clean compile exec:java
